logging:
  level:
    root: WARN
    com.inteam.hakaton.service.impl: DEBUG
    com.inteam.hakaton.controller: DEBUG

spring:
  application:
    name: hakaton
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}?currentSchema=hak
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    hikari:
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
  flyway:
    placeholders:
      dbuser: ${spring.datasource.username}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    schemas: hak
    user: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        format_sql: true
      jdbc:
        batch_size: 250
      order_inserts: true
      order_updates: true
      batch_versioned_data: true

feign:
  client:
    config:
      default:
        readTimeout: 3600000
        connectTimeout: 3600000


predication:
  url: ${DB_HOST_ML:localhost}:${DB_PORT_ML:5000}

